#!/bin/bash
cmdname=`basename $0`
function usage()
{
    echo "$cmdname [Options] <samplepairlist> <build>" 1>&2
    echo '   <samplepairlist>: text file of ChIP/Input sample pairs' 1>&2
    echo '   <build>: genome build (e.g., hg38)' 1>&2
    echo '   Options:' 1>&2
    echo '      -q <qvalue>: threshould of MACS2 (defalt: 0.05)' 1>&2
    echo '      -m <mdir>: output direcotyr (defalt: "macs")' 1>&2
}

qval=0.05
mdir=macs

while getopts q: option
do
    case ${option} in
	q) qval=${OPTARG};;
	d) mdir=${OPTARG};;
        *)
	    usage
	    exit 1
	    ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

samplepairlist=$1
build=$2

if test $build = "hg19" -o $build = "hg38"; then
    sp="hs"
elif test $build = "mm9" -o $build = "mm10" -o $build = "mm39"; then
    sp="mm"
elif test $build = "ce11"; then
    sp="ce"
elif test $build = "dm3" -o test $build = "dm6" -o test $build = "dm7"; then
    sp="dm"
else
    sp="1e8"
fi

ex(){ echo $1; eval $1; }

IFS=","
while read LINE; do
    LINE=($LINE)
    chip=${LINE[0]}
    input=${LINE[1]}
    label=${LINE[2]}
    mode=${LINE[3]}
    IPbam=bam/$chip-bowtie2-$build.sort.bam
    Inputbam=bam/$input-bowtie2-$build.sort.bam

    if test "$input" = ""; then
	macs.sh -s $sp -q $qval -d $mdir $IPbam none $label $mode
    else
	macs.sh -s $sp -q $qval -d $mdir $IPbam $Inputbam $label $mode
    fi
done < $samplepairlist
