#!/bin/bash
cmdname=`basename $0`
function usage()
{
    echo "$cmdname [Options] <samplepairlist> <prefix> <build> <Ddir>" 1>&2
    echo '   <samplepairlist>: text file of ChIP/Input sample pairs' 1>&2
    echo '   <prefix>: output prefix' 1>&2
    echo '   <build>: genome build (e.g., hg38)' 1>&2
    echo '   <Ddir>: directory of bowtie2 index' 1>&2
    echo '   Options:' 1>&2
    echo '      -b <int>: binsize (defalt: 100)' 1>&2
    echo '      -l <int>: line size for each page (defalt: 1000 (kbp))' 1>&2
    echo '      -d <str>: directory of parse2wig+ (default: parse2wigdir+)' 1>&2
    echo '      -y <str>: postfix of .bw files to be used (default: "-bowtie2-<build>-raw-GR")' 1>&2
    echo '      -P : additional parameters for DROMPA+ (shouled be quated)' 1>&2
    echo '      -G : genome-wide view (100kbp)' 1>&2
    echo "   Example:" 1>&2
    echo "      $cmdname samplelist.txt chip-seq hg38 Database/Ensembl-GRCh38" 1>&2
}

binsize=100
linesize=1000
pdir=parse2wigdir+
post_predefined=""
GV=0
param=""
while getopts P:b:l:d:o:y:G option
do
    case ${option} in
	P) param=${OPTARG};;
        b) binsize=${OPTARG};;
        l) linesize=${OPTARG};;
        d) pdir=${OPTARG};;
        y) post_predefined=${OPTARG};;
        G) GV=1;;
	*)
	    usage
	    exit 1
	    ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 4 ]; then
  usage
  exit 1
fi

samplepairlist=$1
prefix=$2
build=$3
Ddir=$4

if test "$post_predefined" = ""; then
    post=-bowtie2-$build-raw-GR
else
    post=$post_predefined
fi

ex(){ echo $1; eval $1; }

gt=$Ddir/genometable.txt

mkdir -p log
if test $GV -eq 1; then
    # GV mode
    ideogram=/opt/DROMPAplus/data/ideogram/$build.tsv
    GC=$Ddir/GCcontents/
    GD=$Ddir/gtf_chrUCSC/genedensity

    sGV=""
#    while IFS=, read chip input label mode peak; do
    while read LINE; do
        LINE=(${LINE//,/ })
        chip=${LINE[0]}
        input=${LINE[1]}
        label=${LINE[2]}

        if test "$input" != ""; then
            sGV="$sGV -i $pdir/$chip$post.100000.bw,$pdir/$input$post.100000.bw,$label"
        else
            echo "sample $chip does not have the input sample. skipped.."
        fi
    done < $samplepairlist

    head=`basename $prefix`
    ex "drompa+ GV $param $sGV -o $prefix.GV.100000 --gt $gt --ideogram $ideogram --GC $GC --gcsize 500000 --GD $GD --gdsize 500000 >& log/drompa+.$head.GV.100000"
else
    s=""
#    while IFS=, read chip input label mode peak; do
    while read LINE; do
        LINE=(${LINE//,/ })
        chip=${LINE[0]}
        input=${LINE[1]}
        label=${LINE[2]}
        peak=${LINE[4]}

        if test "$input" != ""; then
            s="$s -i $pdir/$chip$post.$binsize.bw,$pdir/$input$post.$binsize.bw,$label,$peak"
        else
            s="$s -i $pdir/$chip$post.$binsize.bw,,$label,$peak"
        fi
    done < $samplepairlist

    gene=$Ddir/gtf_chrUCSC/chr.gene.refFlat
    head=`basename $prefix`
    ex "drompa+ PC_SHARP $param $s -o $prefix.PCSHARP.$binsize --gt $gt -g $gene --ls $linesize --showchr --callpeak >& log/drompa+.$head.PCSHARP.$binsize"
    rm $prefix.PCSHARP.$binsize.pdf
fi
