#!/bin/bash
cmdname=`basename $0`
function usage()
{
    echo "$cmdname [Options] <samplepairlist> <build>" 1>&2
    echo '   <samplepairlist>: text file of ChIP/Input sample pairs' 1>&2
    echo '   <build>: genome build (e.g., hg38)' 1>&2
    echo '   Options:' 1>&2
    echo '      -q <qvalue>: threshould of MACS2 (defalt: 0.05)' 1>&2
    echo '      -d <mdir>: output direcoty (defalt: "macs")' 1>&2
}

qval=0.05
mdir=macs

while getopts q:d: option
do
    case ${option} in
	q) qval=${OPTARG};;
	d) mdir=${OPTARG};;
        *)
	    usage
	    exit 1
	    ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

samplepairlist=$1
build=$2

ex(){ echo $1; eval $1; }

newlist=$mdir/$samplepairlist
rm -rf $newlist
#while IFS=, read chip input label mode; do
while read LINE; do
    LINE=(${LINE//,/ })
    chip=${LINE[0]}
    input=${LINE[1]}
    label=${LINE[2]}
    mode=${LINE[3]}

    IPbam=bam/$chip-bowtie2-$build.sort.bam
    Inputbam=bam/$input-bowtie2-$build.sort.bam

    if test "$mode" = ""; then
       mode="sharp"
    fi
    if test $mode = "sharp" -o $mode = "nomodel"; then
	peak=$mdir/${label}_peaks.narrowPeak
    else
	peak=$mdir/${label}_peaks.broadPeak
    fi
    if test "$input" = ""; then
       macs.sh -q $qval -d $mdir $IPbam none $label $build $mode
    else
       macs.sh -q $qval -d $mdir $IPbam $Inputbam $label $build $mode
    fi
    echo "$chip,$input,$label,$mode,$peak" >> $newlist
done < $samplepairlist

#cat $samplepairlist | awk -F',' 'BEGIN{OFS = ","} {printf("%s,%s,%s,%s,'$mdir'/%s_peaks.narrowPeak\n", $1, $2, $3, $4, $1) }' > $mdir/$samplepairlist
