#!/bin/bash
cmdname=`basename $0`
function usage()
{
    echo "$cmdname [Options] <samplepairlist> <build>" 1>&2
    echo '   <samplepairlist>: text file of ChIP/Input sample pairs' 1>&2
    echo '   <build>: genome build (e.g., hg38)' 1>&2
    echo '   Options:' 1>&2
    echo '      -D : directory for execution (defalt: "Churros_result")' 1>&2
    echo '      -q : threshould of MACS2 (defalt: 0.05)' 1>&2
    echo '      -b : bam direcoty (defalt: "bam")' 1>&2
    echo '      -d : output direcoty (defalt: "macs")' 1>&2
    echo '      -F : overwrite MACS2 resilts if exist (defalt: skip)' 1>&2
    echo '      -p : number of CPUs (defalt: 4)' 1>&2
}

qval=0.05
mdir=macs
bamdir=bam
ncore=4
chdir="Churros_result"
force=""

while getopts D:b:q:d:p:F option
do
    case ${option} in
	D) chdir=${OPTARG};;
	b) bamdir=${OPTARG};;
	q) qval=${OPTARG};;
	d) mdir=${OPTARG};;
	p) ncore=${OPTARG};;
	F) force="-F";;
        *)
	    usage
	    exit 1
	    ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

samplepairlist=$1
build=$2

if test ! -e $samplepairlist; then
    echo "Error: $samplepairlist does not exist."
    exit 1
fi

ex(){ echo $1; eval $1; }

echo "Churros callpeak: $samplepairlist"

mdir_original=`basename $mdir`
mdir=$chdir/$mdir_original
bamdir=$chdir/`basename $bamdir`

mkdir -p $mdir
newlist=$mdir/samplepairlist.txt
rm -rf $newlist
array=""
peakarray=""
while read LINE; do
    array="$array $LINE"

    LINE=(${LINE//,/ })
    chip=${LINE[0]}
    input=${LINE[1]}
    label=${LINE[2]}
    mode=${LINE[3]}
    if test "$mode" = ""; then
       mode="sharp"
    fi
    if test $mode = "sharp" -o $mode = "sharp-nomodel"; then
       peak=$mdir_original/${label}_peaks.narrowPeak
       peak_chdir=$mdir/${label}_peaks.narrowPeak
    else
       peak=$mdir_original/${label}_peaks.broadPeak
       peak_chdir=$mdir/${label}_peaks.broadPeak
    fi
    echo "$chip,$input,$label,$mode,$peak" >> $newlist
    peakarray="$peakarray -f $peak_chdir -l $label"
done < $samplepairlist

do_macs(){
    LINE=$1
    build=$2
    bamdir=$3
    mdir=$4
    newlist=$5
    qval=$6
    force=$7

    LINE=(${LINE//,/ })
    chip=${LINE[0]}
    input=${LINE[1]}
    label=${LINE[2]}
    mode=${LINE[3]}
    flen=${LINE[4]}
    IPbam=$bamdir/$chip-bowtie2-$build.sort.bam
    Inputbam=$bamdir/$input-bowtie2-$build.sort.bam

    if test "$mode" = ""; then mode="sharp"; fi

    if test $mode = "sharp" -o $mode = "sharp-nomodel"; then
	peak=$mdir/${label}_peaks.narrowPeak
	if test "$flen" != ""; then
	    mode="sharp-nomodel"
	    flen="-f $flen"
	fi
    else
	peak=$mdir/${label}_peaks.broadPeak
	if test "$flen" != ""; then
	    mode="broad-nomodel"
	    flen="-f $flen"
	fi
    fi
    if test "$input" = ""; then
	macs.sh $force -q $qval -d $mdir $flen $IPbam none $label $build $mode
    else
	macs.sh $force -q $qval -d $mdir $flen $IPbam $Inputbam $label $build $mode
    fi
}
export -f do_macs

echo ${array[@]} | tr ' ' '\n' | xargs -n1 -I {} -P $ncore bash -c "do_macs {} $build $bamdir $mdir $newlist $qval $force"

echo "churros_callpeak done."
echo -en "churros peak comparison..."

## all
jaccard.pl $peakarray -n 10000000 > $mdir/jaccard.all.tsv
Rscript /opt/scripts/matrix_heatmap.R -i=$mdir/jaccard.all.tsv -o=$mdir/jaccard.all -clst -fsize=1 -method=ward.D2 -k=2

jaccard.pl $peakarray -n 10000 > $mdir/jaccard.10000.tsv
Rscript /opt/scripts/matrix_heatmap.R -i=$mdir/jaccard.10000.tsv -o=$mdir/jaccard.10000 -clst -fsize=1 -method=ward.D2 -k=2

echo "done."
