#!/bin/bash
cmdname=`basename $0`
function usage()
{
    echo "$cmdname [Options] <samplepairlist> <build>" 1>&2
    echo '   <samplepairlist>: text file of ChIP/Input sample pairs' 1>&2
    echo '   <build>: genome build (e.g., hg38)' 1>&2
    echo '   Options:' 1>&2
    echo '      -q : threshould of MACS2 (defalt: 0.05)' 1>&2
    echo '      -b : bam direcoty (defalt: "bam")' 1>&2
    echo '      -d : output direcoty (defalt: "macs")' 1>&2
    echo '      -p : number of CPUs (defalt: 4)' 1>&2
}

qval=0.05
mdir=macs
bamdir=bam
ncore=4

while getopts b:q:d:p: option
do
    case ${option} in
	b) bamdir=${OPTARG};;
	q) qval=${OPTARG};;
	d) mdir=${OPTARG};;
	p) ncore=${OPTARG};;
        *)
	    usage
	    exit 1
	    ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

samplepairlist=$1
build=$2

if test ! -e $samplepairlist; then
    echo "Error: $samplepairlist does not exist."
    exit 1
fi

ex(){ echo $1; eval $1; }

echo "Churros comparepeak: $samplepairlist"


#####

b1=peak1.bed
b2=peak2.bed
l1=Control
l2=siRad21
pdfname="Venn.pdf"

compare_bs -1 $b1 -2 $b2 -nobs > temp
n1=`parsecomparebs.pl temp | cut -f1`
n2=`parsecomparebs.pl temp | cut -f2`
o1=`parsecomparebs.pl temp | cut -f3`
o2=`parsecomparebs.pl temp | cut -f7`

R -e "library(VennDiagram); pdf('$pdfname'); draw.pairwise.venn(area1=$n1, area2=$n2, cross.area=$o2, category=c('$l1','$l2'), cat.pos=c(0,33), cat.dist=c(0.01,0.04), col=c(colors()[139],'blue') , alpha=0.5 , fill=c(colors()[72],'blue'), ext.pos=5); dev.off()"
rm temp

#####



mkdir -p $mdir
newlist=$mdir/samplepairlist.txt
rm -rf $newlist
array=""
while read LINE; do
    array="$array $LINE"

    LINE=(${LINE//,/ })
    chip=${LINE[0]}
    input=${LINE[1]}
    label=${LINE[2]}
    mode=${LINE[3]}
    if test "$mode" = ""; then
       mode="sharp"
    fi
    if test $mode = "sharp" -o $mode = "sharp-nomodel"; then
       peak=$mdir/${label}_peaks.narrowPeak
    else
       peak=$mdir/${label}_peaks.broadPeak
    fi
    echo "$chip,$input,$label,$mode,$peak" >> $newlist
done < $samplepairlist

do_macs(){
    LINE=$1
    build=$2
    bamdir=$3
    mdir=$4
    newlist=$5
    qval=$6

    LINE=(${LINE//,/ })
    chip=${LINE[0]}
    input=${LINE[1]}
    label=${LINE[2]}
    mode=${LINE[3]}
    flen=${LINE[4]}
    IPbam=$bamdir/$chip-bowtie2-$build.sort.bam
    Inputbam=$bamdir/$input-bowtie2-$build.sort.bam

    if test "$mode" = ""; then mode="sharp"; fi

    if test $mode = "sharp" -o $mode = "sharp-nomodel"; then
	peak=$mdir/${label}_peaks.narrowPeak
	if test "$flen" != ""; then
	    mode="sharp-nomodel"
	    flen="-f $flen"
	fi
    else
	peak=$mdir/${label}_peaks.broadPeak
	if test "$flen" != ""; then
	    mode="broad-nomodel"
	    flen="-f $flen"
	fi
    fi
    if test "$input" = ""; then
	macs.sh -q $qval -d $mdir $flen $IPbam none $label $build $mode
    else
	macs.sh -q $qval -d $mdir $flen $IPbam $Inputbam $label $build $mode
    fi
}
export -f do_macs

echo ${array[@]} | tr ' ' '\n' | xargs -n1 -I {} -P $ncore bash -c "do_macs {} $build $bamdir $mdir $newlist $qval"

echo "churros_callpeak done."
