#!/bin/bash
cmdname=`basename $0`
function usage()
{
    echo "$cmdname [Options] <samplepairlist> <prefix> <build> <Ddir>" 1>&2
    echo '   <samplepairlist>: text file of ChIP/Input sample pairs' 1>&2
    echo '   <prefix>: output prefix (directory will be omitted)' 1>&2
    echo '   <build>: genome build (e.g., hg38)' 1>&2
    echo '   <Ddir>: directory of bowtie2 index' 1>&2
    echo '   Options:' 1>&2
    echo '      -b <int>: binsize (defalt: 100)' 1>&2
    echo '      -l <int>: line size for each page (defalt: 1000 (kbp))' 1>&2
    echo '      -d <str>: directory of parse2wig+ (default: parse2wigdir+)' 1>&2
    echo '      -y <str>: postfix of .bw files to be used (default: "-bowtie2-<build>-raw-GR")' 1>&2
    echo '      -p: show p-value distribution instead of read distribution' 1>&2
    echo '      -P : additional parameters for DROMPA+ (shouled be quated)' 1>&2
    echo '      -G : genome-wide view (100kbp)' 1>&2
    echo '      -D : directory for execution (defalt: "Churros_result")' 1>&2
    echo "   Example:" 1>&2
    echo "      $cmdname samplelist.txt chip-seq hg38 Database/Ensembl-GRCh38" 1>&2
}

binsize=100
linesize=1000
pdir=parse2wigdir+
post_predefined=""
GV=0
showpvalue=0
param=""
chdir="Churros_result"

while getopts P:b:l:d:o:y:pGD: option
do
    case ${option} in
	P) param=${OPTARG};;
        b) binsize=${OPTARG};;
        l) linesize=${OPTARG};;
        d) pdir=${OPTARG};;
        y) post_predefined=${OPTARG};;
	p) showpvalue=1;;
        G) GV=1;;
        D) chdir=${OPTARG};;
	*)
	    usage
	    exit 1
	    ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 4 ]; then
  usage
  exit 1
fi

samplepairlist=$1
prefix=$2
build=$3
Ddir=$4
pdir=$chdir/$pdir

if test ! -e $samplepairlist; then
    echo "Error: $samplepairlist does not exist."
    exit 1
fi

if test "$post_predefined" = ""; then
    post=-bowtie2-$build-raw-GR
else
    post=$post_predefined
fi

if test $showpvalue -eq 1; then
    param="$param --showctag 0 --showpenrich 1"
fi

ex(){ echo $1; eval $1; }

gt=$Ddir/genometable.txt
if test ! -e $gt; then
    echo "Error: $gt does not exist. Please make it by 'download_genomedata.sh'."
    exit 1
fi

pdfdir=$chdir/pdf
mkdir -p $pdfdir

if test $GV -eq 1; then
    # GV mode
    ideogram=/opt/DROMPAplus/data/ideogram/$build.tsv
    GC=$Ddir/GCcontents/
    GD=$Ddir/gtf_chrUCSC/genedensity

    sGV=""
#    while IFS=, read chip input label mode peak; do
    while read LINE; do
        LINE=(${LINE//,/ })
        chip=${LINE[0]}
        input=${LINE[1]}
        label=${LINE[2]}

        if test "$input" != ""; then
            sGV="$sGV -i $pdir/$chip$post.100000.bw,$pdir/$input$post.100000.bw,$label"
        else
            echo "sample $chip does not have the input sample. skipped.."
        fi
    done < $samplepairlist

    head=`basename $prefix`

    echo -en "Command: "
    echo "drompa+ GV $param $sGV -o $pdfdir/$head.GV.100000 --gt $gt --ideogram $ideogram --GC $GC --gcsize 500000 --GD $GD --gdsize 50000 >& $pdfdir/$head.GV.100000.log" > $pdfdir/$head.GV.100000.log
    ex "drompa+ GV $param $sGV -o $pdfdir/$head.GV.100000 --gt $gt --ideogram $ideogram --GC $GC --gcsize 500000 --GD $GD --gdsize 500000 | tee -a $pdfdir/$head.GV.100000.log"
else
    s=""
#    while IFS=, read chip input label mode peak; do
    while read LINE; do
        LINE=(${LINE//,/ })
        chip=${LINE[0]}
        input=${LINE[1]}
        label=${LINE[2]}
        peak=${LINE[4]}

        if test "$peak" != ""; then
            peak=$chdir/$peak
        fi

        if test "$input" != ""; then
            s="$s -i $pdir/$chip$post.$binsize.bw,$pdir/$input$post.$binsize.bw,$label,$peak"
        else
            s="$s -i $pdir/$chip$post.$binsize.bw,,$label,$peak"
        fi
    done < $samplepairlist

    gene=$Ddir/gtf_chrUCSC/chr.gene.refFlat
    head=`basename $prefix`

    echo -en "Command: "
    echo "drompa+ PC_SHARP $param $s -o $pdfdir/$head.PCSHARP.$binsize --gt $gt -g $gene --ls $linesize --showchr --callpeak >& $pdfdir/$head.PCSHARP.$binsize.log" > $pdfdir/$head.PCSHARP.$binsize.log
    ex "drompa+ PC_SHARP $param $s -o $pdfdir/$head.PCSHARP.$binsize --gt $gt -g $gene --ls $linesize --showchr --callpeak | tee -a $pdfdir/$head.PCSHARP.$binsize.log"
    rm $prefix.PCSHARP.$binsize.pdf
fi
