sing="singularity exec --bind /work,/work2,/work3 /work3/SingularityImages/churros.1.4.1.sif"
#sing="singularity exec churros.sif"

# This script uses the bam files generated by the yeast tutorial in the tutorial/yeast/ directory.
# Try it if you have not already done so.
# Then copy the generated bam files from the Churros_result/sacCer3/ directory to here.
#cp -r ../yeast/Churros_result/sacCer3/bam/ ./bam/

$sing churros --preset scer samplelist.txt samplepairlist.txt sacCer3 /work/Database/Database_fromDocker/Referencedata_sacCer3/
