### Churros: Docker image for ChIP-seq analysis
FROM rnakato/database:2022.12
MAINTAINER Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>

WORKDIR /opt
USER root

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    build-essential \
    cutadapt \
    fastqc \
    libboost-all-dev \
    libbz2-dev \
    libcurl4-gnutls-dev \
    libgtkmm-3.0-dev \
    libgzstream0 \
    libgzstream-dev \
    liblzma-dev \
    libz-dev \
    lmodern \
    cmake \
    curl \
    pandoc \
    pigz \
    texlive-fonts-recommended \
    texlive-xetex \
    && apt-get clean \
    && rm -rf /var/lib/apt/list

# R packages
RUN R -e "BiocManager::install(c('edgeR', 'DESeq2', 'preprocessCore', 'ChIPseeker', 'Rsamtools'))" \
    && R -e "install.packages(c('snow', 'snowfall', 'bitops', 'caTools', 'VennDiagram'))"

# BWA 0.7.17
COPY bwa-0.7.17.tar.bz2 bwa-0.7.17.tar.bz2
RUN tar xvfj bwa-0.7.17.tar.bz2 \
    && cd bwa-0.7.17 \
    && make \
    && rm /opt/bwa-0.7.17.tar.bz2

# Bowtie1.3.1
COPY bowtie-1.3.1-linux-x86_64.zip bowtie-1.3.1-linux-x86_64.zip
RUN unzip bowtie-1.3.1-linux-x86_64.zip \
    && rm bowtie-1.3.1-linux-x86_64.zip

# Bowtie1.1.2 (for colorspace data)
COPY bowtie-1.1.2-linux-x86_64.zip bowtie-1.1.2-linux-x86_64.zip
RUN unzip bowtie-1.1.2-linux-x86_64.zip \
    && rm bowtie-1.1.2-linux-x86_64.zip

# Bowtie2.4.5
COPY bowtie2-2.4.5-linux-x86_64.zip bowtie2-2.4.5-linux-x86_64.zip
RUN unzip bowtie2-2.4.5-linux-x86_64.zip \
    && rm bowtie2-2.4.5-linux-x86_64.zip

# Chromap 0.2.1
COPY chromap-0.2.1_x64-linux.tar.bz2 chromap-0.2.1_x64-linux.tar.bz2
RUN tar xvfj chromap-0.2.1_x64-linux.tar.bz2 \
    && rm chromap-0.2.1_x64-linux.tar.bz2 \
    && mv chromap /opt/bin

# ChromHMM v1.23, ChromImpute v1.0.3
COPY ChromHMM.jar /opt/bin/ChromHMM.jar
COPY ChromImpute.jar /opt/bin/ChromImpute.jar

# Bismark v0.22.3
COPY Bismark.0.22.3.tar.gz Bismark.0.22.3.tar.gz
RUN tar zxvf Bismark.0.22.3.tar.gz \
    && rm Bismark.0.22.3.tar.gz

# fastp, bedtools v2.30.0
COPY fastp /opt/bin/fastp
COPY bedtools /opt/bin/bedtools

# TrimGalore v0.6.7
COPY TrimGalore-0.6.7.tar.gz TrimGalore-0.6.7.tar.gz
RUN tar zxvf TrimGalore-0.6.7.tar.gz \
    && rm TrimGalore-0.6.7.tar.gz

# MultiQC, deepTools, intervene
RUN pip install --no-cache-dir epilogos multiqc deeptools intervene

# HOMER
RUN mkdir HOMER && cd HOMER \
    && mkdir bin cpp update \
    && wget http://homer.ucsd.edu/homer/configureHomer.pl \
    && perl configureHomer.pl -install human-o \
    && perl configureHomer.pl -install human-p \
    && perl configureHomer.pl -install mouse-o \
    && perl configureHomer.pl -install mouse-p \
    && perl configureHomer.pl -install zebrafish-o \
    && perl configureHomer.pl -install yeast-o

# DROMPAplus
RUN git clone --recursive https://github.com/rnakato/DROMPAplus \
    && cd DROMPAplus \
    && git submodule foreach git pull origin master \
    && make

### To be considered
# NextFlow
#RUN curl -s https://get.nextflow.io | bash \
#    && mv nextflow /opt/bin
# Epilogos (https://github.com/meuleman/epilogos)

# scripts
ENV CDIR Churros
COPY $CDIR /opt/$CDIR
RUN chmod a+x /opt/$CDIR/* /opt/bin/*
# MOSAiCS
RUN make -C /opt/$CDIR/MOSAiCS_mappability/

COPY rose /opt/ROSE
ENV PYTHONPATH $PYTHONPATH:/opt/ROSE/

ENV PATH ${PATH}:/opt/scripts:/opt/$CDIR:/opt/SSP/bin:/opt/DROMPAplus/bin:/opt/DROMPAplus/submodules/cpdf/Linux-Intel-64bit:/opt/DROMPAplus/otherbins:/opt/bin:/opt/bwa-0.7.17:/opt/bowtie-1.3.1-linux-x86_64:/opt/bowtie2-2.4.5-linux-x86_64:/opt/HOMER/bin/:/opt/ROSE/:/opt/Bismark-0.22.3/:/opt/TrimGalore-0.6.7/

USER ubuntu
CMD ["/bin/bash"]
