#!/bin/bash
cmdname=`basename $0`
function usage()
{
    echo "$cmdname [Options] <samplelist> <build>" 1>&2
    echo '   <samplelist>: text file of samples' 1>&2
    echo '   <build>: genome build (e.g., hg38)' 1>&2
    echo '   Options:' 1>&2
    echo '      -d : output directory (defalt: "compare")' 1>&2
    echo '      -m: consider genome mappability in parse2wig+' 1>&2
    echo '      -D : directory for execution (defalt: "Churros_result")' 1>&2
    echo '      -y <str>: param string of parse2wig+ files to be used (default: "-bowtie2-<build>-raw-GR")' 1>&2
}

odir=comparison
chdir="Churros_result"
mp=0
post_predefined=""

while getopts d:mD:y: option
do
    case ${option} in
	d) odir=${OPTARG};;
        m) mp=1;;
	D) chdir=${OPTARG};;
   	y) post_predefined=${OPTARG};;
        *)
	    usage
	    exit 1
	    ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

samplelist=$1
build=$2

if test ! -e $samplelist; then
    echo "Error: $samplepairlist does not exist."
    exit 1
fi

ex(){ echo $1; eval $1; }

odir=$chdir/`basename $odir`
mkdir -p $odir

if test "$post_predefined" = ""; then
    if test $mp -eq 1; then
        post=-bowtie2-$build-raw-mpbl-GR
    else
        post=-bowtie2-$build-raw-GR
    fi
else
    post=$post_predefined
fi

while read LINE; do
    LINE=($LINE)
    prefix=${LINE[0]}
    array="$array `ls $chdir/parse2wigdir+/$prefix$post.100.bw`"

    sample=`ls $chdir/parse2wigdir+/$prefix$post.100000.bw 2> /dev/null`
    if test "$sample" != ""; then array100k="$array100k $sample"; fi
done < $samplelist
echo $array100k

ofile=$odir/margedbin.npz
multiBigwigSummary bins -b $array -o $ofile
convertlabel_deeptools_npz.py $ofile $odir/margedbin_renamed.npz $post.100.bw
mv $odir/margedbin_renamed.npz $ofile

param="--corMethod spearman --skipZeros -in $ofile"
plotCorrelation $param --plotTitle "Spearman Correlation (100-bp bin)" --whatToPlot scatterplot \
                -o $odir/scatterplot_SpearmanCorr_bigwigScores.100bp.png \
                --outFileCorMatrix $odir/SpearmanCorr_bigwigScores.100bp.tab
plotCorrelation $param --plotTitle "Spearman Correlation (100-bp bin)" --whatToPlot heatmap --colorMap RdYlBu_r --plotNumbers \
                -o $odir/heatmap_SpearmanCorr_readCounts.100bp.png \
                --outFileCorMatrix $odir/SpearmanCorr_readCounts.100bp.tab

if test "$array100k" != ""; then
    ofile=$odir/margedbin.100k.npz
    multiBigwigSummary bins -b $array100k -o $ofile
    convertlabel_deeptools_npz.py $ofile $odir/margedbin_renamed.npz $post.100000.bw
    mv $odir/margedbin_renamed.npz $ofile

    param="--corMethod spearman --skipZeros -in $ofile"
    plotCorrelation $param --plotTitle "Spearman Correlation (100-kbp bin)" --whatToPlot scatterplot \
                    -o $odir/scatterplot_SpearmanCorr_bigwigScores.100kbp.png \
                    --outFileCorMatrix $odir/SpearmanCorr_bigwigScores.100kbp.tab
    plotCorrelation $param --plotTitle "Spearman Correlation (100-kbp bin)" --whatToPlot heatmap --colorMap RdYlBu_r --plotNumbers \
                    -o $odir/heatmap_SpearmanCorr_readCounts.100kbp.png \
                    --outFileCorMatrix $odir/SpearmanCorr_readCounts.100kbp.tab
fi
