#!/bin/bash
# Copyright(c) Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>
# All rights reserved.

cmdname=`basename $0`
function usage()
{
    echo "$cmdname [Options] <region> <peak directory>" 1>&2
    echo '   <region>: BED file of regions to analyze' 1>&2
    echo '   <peak directory>: Directory containing input peak files' 1>&2
    echo '   Options:' 1>&2
    echo '      -k <int>: number of clusters (default: 3)' 1>&2
    echo '      -b <int>: bin size (default: 1000)' 1>&2
    echo '      -s <str>: sort name (default: "defaultUseFirstColumn")' 1>&2
    echo '      -l <str>: sample label TSV file' 1>&2
    echo '      -m <str>: clustering method (default: "minikmeans")' 1>&2
    echo '      -o <str>: output directory (default: "output_binary")' 1>&2
    echo '   Example:' 1>&2
    echo '      $cmdname refregion.bed peakdir/' 1>&2
}

# Set default values for optional arguments
kcluster=3
sortname="defaultUseFirstColumn"
outdir="output_binary"
samplelabel=""
clustermethod="minikmeans"

# Parse command line arguments
while getopts "k:s:o:l:n:m:" opt; do
  case ${opt} in
    k) kcluster=${OPTARG};;
    s) sortname=${OPTARG};;
    o) outdir=${OPTARG};;
    l) samplelabel=${OPTARG};;
    m) clustermethod=${OPTARG};;
    \?)
      echo "Invalid option: -${OPTARG}" >&2
	    usage
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

# Assign values to required positional arguments
region=$1
directory=$2

# Check if required arguments are provided
if [[ -z $region || -z $directory ]]; then
  usage
  exit 1
fi

ex(){ echo $1; eval $1; }

export OPENBLAS_NUM_THREADS=1
export GOTO_NUM_THREADS=1
export OMP_NUM_THREADS=1

#do something after confirming the code
mkdir -p $outdir

# Do something if mode is binary
echo "Binary clustering for $directory."

#make raw matrix
for i in `ls $directory`
do
  cut -f 1-3 $region | intersectBed -a stdin -b $directory/$i -c \
  | awk -v OFS="\t" '{if ($4==0) print 0; else print 1}' \
  | sed "1i$i" > $outdir/binary.$i.tmp
done

cut -f 1-3 $region | sed '1ichromosome\tstart\tend' > $outdir/input.bed3.tmp
paste $outdir/input.bed3.tmp $outdir/binary*tmp > $outdir/Output1_raw_matrix.tsv
rm $outdir/*tmp

if [ "$samplelabel" != "" ]; then
  param="--samplelabeltsv $samplelabel"
fi

peakheatmap.py binary $outdir/Output1_raw_matrix.tsv \
  --sortname $sortname --kcluster $kcluster \
  --outdir $outdir $param --clustermethod $clustermethod
