### Churros: Docker image for ChIP-seq analysis
FROM rnakato/mapping:2024.02.2
LABEL maintainer "Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>"

WORKDIR /opt
USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        fastqc \
        libboost-all-dev \
        libbz2-dev \
        libcurl4-gnutls-dev \
        lld \
        lldb \
        libglpk-dev \
        libgtkmm-3.0-dev \
        libgzstream0 \
        libgzstream-dev \
        liblzma-dev \
        libz-dev \
        lmodern \
        cmake \
        curl \
        pandoc \
        pigz \
        python2 \
        texlive-fonts-recommended \
        texlive-xetex \
    && apt-get clean \
    && rm -rf /var/lib/apt/list

# R packages
RUN R -e "BiocManager::install(c('edgeR', 'DESeq2', 'preprocessCore', 'ChIPseeker', 'Rsamtools', 'rGREAT', 'similaRpeak', 'metagene', 'Imetagene', 'clusterProfiler', 'motifbreakR', \
                                'TxDb.Hsapiens.UCSC.hg38.knownGene', 'TxDb.Hsapiens.UCSC.hg19.knownGene', 'TxDb.Hsapiens.UCSC.mm39.knownGene', 'TxDb.Hsapiens.UCSC.mm10.knownGene'))" \
    && R -e "install.packages(c('snow', 'snowfall', 'bitops', 'caTools', 'VennDiagram'))"

# HOMER v4.11
RUN mkdir HOMER && cd HOMER \
    && mkdir bin cpp update \
    && wget http://homer.ucsd.edu/homer/configureHomer.pl \
    && perl configureHomer.pl -install >& /dev/null \
    && perl configureHomer.pl -install human-o >& /dev/null \
    && perl configureHomer.pl -install human-p >& /dev/null \
    && perl configureHomer.pl -install mouse-o >& /dev/null \
    && perl configureHomer.pl -install mouse-p >& /dev/null \
    && perl configureHomer.pl -install zebrafish-o >& /dev/null \
    && perl configureHomer.pl -install yeast-o >& /dev/null \
    && perl configureHomer.pl -install hg19 >& /dev/null \
    && perl configureHomer.pl -install hg38 >& /dev/null \
    && perl configureHomer.pl -install mm10 >& /dev/null \
    && perl configureHomer.pl -install sacCer3 >& /dev/null \
    && perl configureHomer.pl -install dm6 >& /dev/null \
    && perl configureHomer.pl -install galGal6 >& /dev/null \
    && perl configureHomer.pl -install danRer11 >& /dev/null 

# ChromHMM & ChromImpute
COPY ChromHMM.jar /opt/bin/ChromHMM.jar
COPY ChromImpute.jar /opt/bin/ChromImpute.jar

# Bismark v0.22.3
COPY Bismark.0.22.3.tar.gz Bismark.0.22.3.tar.gz
RUN tar zxvf Bismark.0.22.3.tar.gz \
    && rm Bismark.0.22.3.tar.gz

# fastp
COPY fastp /opt/bin/fastp

# TrimGalore v0.6.7
COPY TrimGalore-0.6.7.tar.gz TrimGalore-0.6.7.tar.gz
RUN tar zxvf TrimGalore-0.6.7.tar.gz \
    && rm TrimGalore-0.6.7.tar.gz

# STITCHIT
RUN git clone https://github.com/SchulzLab/STITCHIT.git \
    && mkdir -p STITCHIT/build \
    && cd STITCHIT/build \
    && cmake .. \
    && make

# DROMPAplus
RUN git clone --recursive https://github.com/rnakato/DROMPAplus \
    && cd DROMPAplus \
    && git submodule foreach git pull origin master \
    && make

# Python (MultiQC, deepTools, intervene, TOBIAS, genmap, sambamba)
# Fix Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)
# https://stackoverflow.com/questions/77617946/solve-conda-libmamba-solver-libarchive-so-19-error-after-updating-conda-to-23
RUN conda install -y -c bioconda genmap sambamba \
    && pip install --no-cache-dir epilogos multiqc intervene argh deeptools tobias cutadapt threadpoolctl==3.1.0

# STARE: https://stare.readthedocs.io/en/latest/index.html
RUN git clone https://github.com/SchulzLab/STARE.git \
    && cd STARE/Code \
    && cmake . \
    && cmake --build .

# SNEEP: https://sneep.readthedocs.io/en/latest/index.html
# Pythonのどのバージョンを入れても入らない
#    && conda create -n sneep python=3.8 \
#    && source activate sneep \
#    && conda install sneep -c bioconda \
#    && pip install --no-cache-dir session-info \
#    && conda deactivate

# scripts
ENV CDIR Churros
COPY $CDIR /opt/$CDIR
RUN chmod a+x /opt/$CDIR/* /opt/bin/*
# MOSAiCS
RUN make -C /opt/$CDIR/MOSAiCS_mappability/

COPY rose /opt/ROSE
ENV PYTHONPATH $PYTHONPATH:/opt/ROSE/

ENV PATH ${PATH}:/opt/scripts:/opt/$CDIR:/opt/SSP/bin:/opt/DROMPAplus/bin:/opt/DROMPAplus/submodules/cpdf/Linux-Intel-64bit:/opt/DROMPAplus/otherbins:/opt/bin:/opt/bwa-0.7.17:/opt/bowtie-1.3.1-linux-x86_64:/opt/bowtie2-2.4.5-linux-x86_64:/opt/HOMER/bin/:/opt/ROSE/:/opt/Bismark-0.22.3/:/opt/TrimGalore-0.6.7/:/opt/STITCHIT/build/core

USER ubuntu
WORKDIR /home/ubuntu
CMD ["churros"]
